name: Cameraman
version: '${project.version}'
main: xyz.shibomb.cameraman.CameramanPlugin
api-version: '1.20'
commands:
  cameraman:
    description: Control the cameraman
    usage: /<command> [set|target|newcomer|rotation]
    permission: cameraman.use
permissions:
  cameraman.use:
    description: Allows use of cameraman commands
    default: op
