name: Cameraman
version: '1.0.1'
main: xyz.shibomb.cameraman.CameramanPlugin
api-version: '1.20'
commands:
  cameraman:
    description: Control the cameraman
    usage: /<command> [set|unset|clear|teleportsmooth|showmessage|target|newcomer|rotation|spectatemode|mobtarget|automob|mobspectatemode|mobnightvision|nightvisionthreshold|distance|height|orbitspeed|orbitdirection|smoothness|flybyduration|craneduration|craneheightmin|craneheightmax|movedirection|movespeed|random|scenic|autoscenic]
    permission: cameraman.use
permissions:
  cameraman.use:
    description: Allows use of cameraman commands
    default: op
