name: Cameraman
version: '1.0-SNAPSHOT'
main: xyz.shibomb.cameraman.CameramanPlugin
api-version: '1.20'
commands:
  cameraman:
    description: Control the cameraman
    usage: /<command> [set|target|clear|newcomer|rotation|mobtarget|automob|teleportsmooth|spectatemode|mobnightvision]
    permission: cameraman.use
permissions:
  cameraman.use:
    description: Allows use of cameraman commands
    default: op
